### ISSUE TITLE
change tun0 to surfshark_ipv6

### ISSUE THREAD

**Issue by ghost** [shin0x/Surfshark-Killswitch-Linux#2]
Hi Shin0x, 

A little change suggestion for  enableKillswitch script.

I am using surfshark gui from AUR.  + Debian tested.
The official Surfshark kill-switch function is not working properly yet.

when surfshark got connected the output is like `surfshark_ipv6` instead of tun.
I changed`tun`  to `_ipv6` in the enableKillswitch.sh, and now it works with the app on all connections. (tcp/udp and wireshark)

`$ sudo ufw allow out on surfshark_ipv6 from any to any`

Thanks for the scripts.

**Comment by shin0x** [comment]
Hey there, thanks for you feedback.
Since I mainly use the OpenVPN files themselves, i would not like to change the values in the current script. 
However I will look into installing the Surfshark Application myself and add a new script, that will have the new interface names.
